### ISSUE TITLE
Can't reproduce cross-dataset test results for LIVE VQA and CSIQ

### ISSUE THREAD

**Issue by qaohv** [pavancm/GREED#2] opened 2021-10-11 09:12 UTC
Hello, Pavan. 

I'm trying to reproduce cross-dataset test results for LIVE-VQA and CSIQ datasets from article "ST-GREED: Space-Time Generalized Entropic Differences for Frame Rate Dependent Video Quality". To do this I use code from repo and pretrained on LIVE-YT-HFR database model from repository ("model_params/bior22.model" and "model_params/bior22_params.mat").
I predicted scores and calculate SROCC for LIVE-VQA and CSIQ datasets. Results are shown in Table 1:

Table 1. SROCC for LIVE VQA and CSIQ datasets.
|    | LIVE VQA |  CSIQ |
|:---------:|:--------:|:-----:|
| ST-GREED  (ours)   |   0.005  | 0.207 |
| ST-GREED  (article)|   0.697  | 0.616 |

Despite the fact that we use the same code and model for cross-dataset test you can see our results differ from article noticeable.
Could you help and specify what we are doing in a wrong way? Code, [csv files](https://github.com/qaohv/GREED/tree/master/csv) and [instructions](https://github.com/qaohv/GREED/blob/master/README.md) to reproduce our results in my [repository](https://github.com/qaohv/GREED).

**Comment by pavancm** [comment] 2021-10-12 00:44
The current release was intended for videos with 1080p and 4K resolution. LIVE-VQA and CSIQ-VQA contain low resolution videos, so it requires some changes in parameters. Since you have raised this issue I am adding support for low resolution videos as well. Please check the updated repo to reflect corresponding changes.

Also there are some missing files for LIVE-VQA in your benchmarking codes. You might need to rectify that in-order to get the reported results.

**Comment by qaohv** [comment] 2021-10-14 04:05
Pavan, thanks for explanation. I tried bior22_lowres.model and got following results:

Table 2. SROCC for LIVE VQA and CSIQ datasets on bior22_lowres.model.
|           | LIVE VQA |  CSIQ |
|:---------:|:--------:|:-----:|
| ST-GREED  (ours)   |   0.674  | 0.616 |
| ST-GREED  (article)|   0.697  | 0.616 |

For CSIQ I got exactly the same results, for LIVE VQA they slightly differ, but I guess it's ok.
One more question: Did you train low resolution models on LIVE-YT-HFR just with other scales param ([3, 4] for resolution < 1080p) ?

**Comment by pavancm** [comment] 2021-10-14 04:43
LIVE-YT-HFR dataset does not contain videos with resolution < 1080p, so the scale parameters [3,4] are applied only on testing videos (here LIVE-VQA and CSIQ data), while for training the original params are used.

Since the issue was resolved I am closing this

**Closed by pavancm** 2021-10-14 04:43 UTC

**Comment by NeighborhoodCoding** [comment] 2022-07-12 07:34
Hi, I just wondering that, How can I download LIVE VQA and CSIQ datasets?
Thx.

**Comment by qaohv** [comment] 2022-07-12 11:26
@NeighborhoodCoding , try find LIVE VQA [here](https://live.ece.utexas.edu/research/quality/)

**Comment by NeighborhoodCoding** [comment] 2022-07-13 00:33
Thank you for your support!
